/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include "SkillCraft_Includes/SkillCraft_Interface"

new PlayerSkill[MAXPLAYERSCUSTOM];

public Plugin:myinfo = 
{
	name = "SkillCraft WCX Bash",
	author = "SkillCraft Team",
	description = "WCX Bash",
	version = "0.1",
}

public OnPluginStart()
{
	//LoadTranslations("w3s.race.humanally.phrases");
}

public On_SC_EventPostHurt(victim,attacker,damage,const String:weapon[32],bool:isWarcraft){
	if(IS_PLAYER(victim)&&IS_PLAYER(attacker)&&victim>0&&attacker>0&&attacker!=victim)
	{
		//decl String:weapon[64];
		//GetEventString(SC_GetVar(SmEvent),"weapon",weapon,63); 
		if(StrEqual(weapon, "crit",false) || StrEqual(weapon, "bash", false) || StrEqual(weapon, "weapon_crit",false) || StrEqual(weapon, "weapon_bash", false))
			return;
		
		new vteam=GetClientTeam(victim);
		new ateam=GetClientTeam(attacker);
		if(vteam!=ateam)
		{
			new Float:percent = SC_GetBuffSumFloat(attacker,fBashChance);
			if((percent > 0.0) && !Hexed(attacker) &&!SC_HasImmunity(victim,Immunity_Skills)&&SC_ChanceModifier(attacker))
			{
				// Bash
				if(SC_Chance(percent) && !SC_GetBuffHasTrue(victim,bBashed) && IsPlayerAlive(attacker))
				{
					// using mastery as primary target for buffs
					new skillid=SC_GetSkill(victim,mastery);
					PlayerSkill[victim] = skillid;
					SC_SetBuff(victim,bBashed,skillid,true);
					new newdamage = SC_GetBuffSumInt(attacker,iBashDamage);
					if(newdamage>0)
						SC_DealDamage(victim,newdamage,attacker,_,"weapon_bash");
					
					SC_FlashScreen(victim,RGBA_COLOR_RED);
					new Float:duration = SC_GetBuffSumFloat(attacker,fBashDuration);
					CreateTimer(duration,UnfreezePlayer,victim);
					
					//PrintHintText(victim,"%T","RcvdBash",victim);
					//PrintHintText(attacker,"%T","Bashed",attacker);
				}
			}
			
		}
	}
}

public Action:UnfreezePlayer(Handle:h,any:victim)
{
	SC_SetBuff(victim,bBashed,PlayerSkill[victim],false);
}



